import '../css/Faq.css';

import { FaqItem } from '../tools/FaqItem';

export function Faq() {
    return <>
        <div className="faq-title">
            <h1>Foire aux questions</h1>
        </div>
        <div className="faq-content">
            <div>
                <h2>Questions générales</h2>
                <div>
                    <FaqItem question={"Qui a créé le clavier Tryhard ?"} answer={"Le clavier Tryhard est une idée originale de CYRILmp4, un créateur de contenu français aux 5M d'abonnés, particulièrement reconnu pour son expertise jeu vidéo. Toujours en quête du matériel gaming idéal, CYRILmp4 a vite réalisé que la plupart des claviers mécaniques, qui figurent pourtant parmi les plus réputés pour le jeu vidéo, étaient uniquement développés aux États-Unis ou en Asie, et n'étaient malheureusement que très peu accessibles en Europe. Il s'est donc entouré de consultants clavier et d'experts en production afin d'arriver à créer le clavier mécanique idéal, accessible en termes de prix, et surtout distribuable en France."}/>
                    <FaqItem question={"Qu'est-ce que la marque Tryhard ?"} answer={"Tryhard est une marque de matériel gaming de haute qualité qui propose des périphériques au design simple et épuré et qui garantit des sensations de frappe uniques. Elle a été développée par CYRILmp4, un créateur de contenu français reconnu pour sa culture et son amour du jeu vidéo."}/>
                    <FaqItem question={"En quoi le clavier Tryhard est-il différent des autres claviers ?"} answer={"Le clavier Tryhard a été pensé et conçu comme le clavier ultime pour joueurs exigeants. > Personnalisation : Grâce à sa technologie hotswap, chaque joueur peut changer ou réparer soi-même les pièces, sans avoir besoin de l'appui d'un expert. Le positionnement sud des LEDs (south facing) permet également d'éviter toute interférence, qu'importe le profil de touches que vous utilisez. > Adaptabilité : Trois modes sont proposés - Bluetooth 5.0, câble USB-C et sans fil 2,4Ghz -, afin de satisfaire les habitudes de connectivité de chacun. > Sensation : Le montage du clavier en gasket mount permet notamment un meilleur amortissement des vibrations ainsi qu'une meilleure stabilité. > Durabilité : Grâce aux matériaux utilisés, aux interrupteurs mécaniques et à ses pièces facilement interchangeables, le clavier Tryhard vous offre une durée de vie plus longue que celle de claviers traditionnels et garantit donc une approche plus écoresponsable de la technologie. > Esthétique : Son design minimaliste et épuré peut s'adapter à n'importe quel setup. A noter que les caractères sont imprimés sur la face avant du clavier."}/>
                    <FaqItem question={"Qu'appelle-t-on un clavier mécanique gasket mount ?"} answer={"Le 'gasket mount' est une méthode de montage utilisée dans la conception de claviers mécaniques. Il se caractérise par l'utilisation de joints en caoutchouc (gaskets) situés entre la plaque du clavier et le boîtier pour fixer les interrupteurs mécaniques. Cette approche diffère du montage traditionnel par plaque ou 'plate mount' où les interrupteurs sont directement fixés à une plaque métallique. Pourquoi avoir choisi cette option avec Tryhard ? Car le gasket mount contribue à améliorer le confort de frappe, fournit une sensation pus douce de la saisie, offre une meilleure stabilité à l'ensemble du clavier et surtout permet à chacun de personnaliser les pièces sans avoir recours à l'intervention d'une personne tierce."}/>
                    <FaqItem question={"J'aimerais plus de précisions sur les composants du clavier."} answer={"Notre clavier Tryhard est un clavier compact, format 65%, qui ne comprend que les touches essentielles. Ces dernières, aux profils cherry, sont fabriquées en polybutylène téréphtalate (PBT), un matériau plastique réputé pour sa durabilité, sa résistance à l'usure et sa texture agréable au toucher. Il est également équipé d'un stabilisateur prélubrifié monté sur une plaque en métal, pour ajouter plus de poifs et de stabilité, ainsi que d'un amortissement de plaque en poron et d'un amortisseur de boitier en silicone. Les interrupteurs mécaniques (ou switches) sont de modèle CIDOO. Le bouton de volume est en aluminium noir, pour une finition plus élégante et solide. Le boitier et la double-encadrure sont quant à eux en acrylonitrile butadiène styrène (ABS)."}/>
                    <FaqItem question={"Je ne joue pas ou très peu. Puis-je utiliser le clavier Tryhard pour de la bureautique uniquement ?"} answer={"Évidemment ! Notre clavier Tryhard est conçu pour tout type d'utilisation, avec un confort de frappe accru et un design épuré, lui permettant de s'intégrer dans n'importe quel setup."}/>
                    <FaqItem question={"Le clavier Tryhard est en rupture de stock. Puis-je en commander malgré tout ?"} answer={"Oui, tout à fait ! Si la première série est déjà vendue, vous pouvez dès à présent en précommander un nouveau. Dès que la palier de 2000 nouvelles unités est atteint, la production sera lancée et les claviers livrés dans la foulée. Vous serez alertés par email ! Pour toutes questions complémentaires, vous pouvez vous référer à la section 'Précommandes'."}/>
                    <FaqItem question={"Y aura-t-il d'autres produits Tryhard ?"} answer={"Certainement 👀. Vos retours seront d'ailleurs très importants pour nous aider à nous améliorer et continuer de vous proposer les meilleurs produits possibles !"}/>
                    <FaqItem question={"Où est fabriqué le clavier Tryhard ?"} answer={"Le clavier Tryhard a été pensé et designé en France, avec l'appui d'un consultant expert en clavier. La production s'est ensuite faite en Chine, par l'intermédiaire de SH Global, notre partenaire privilégié qui se caractérise par plus de 60 ans d'expérience dans la fabrication et la logistique. Leur expertise garantit une qualité exceptionnelle et une gestion méticuleuse à chaque étape du processus de création, fabrication et de la logistique."}/>
                </div>
            </div>
            <div>
                <h2>Questions relatives à la livraison</h2>
                <div>
                    <FaqItem question={"Quels sont les délais de livraison ?"} answer={"Pour les 2000 premières préventes, l'expédition des colis ne sera possible qu'à partir du 22 décembre en France métropolitaine. Une fois le 22 décembre passé, il faudra compter entre 1 à 2 jours de livraison jusqu'à votre porte. Attention cependant, en raison de la période des fêtes de fin d'année, les délais peuvent être plus longs qu'habituellement. Nous faisons cependant notre maximum pour que vous l'ayez à Noël ! Passées les fêtes de fin d'année, si nous avons encore du stock disponible, la livraison se fera simplement en 1 à 2 jours ouvrés."}/>
                    <FaqItem question={"Quel est le montant des frais de livraison ?"} answer={"Les frais de livraison sont de 7,50 euros en France métropolitaine pour une commande de 1 à 3 claviers. Au-delà de 3 claviers, des frais s'ajoutent. Pour la Belgique, le Luxembourg, les Pays-Bas et l'Allemagne, comptez 12 euros pour une commande de 1 à 2 claviers. Au-delà de 2 claviers, des frais s'ajoutent."}/>
                    <FaqItem question={"Comment suivre ma commande ?"} answer={"Une fois votre achat effectué, vous recevrez un e-mail de confirmation de commande. Dès que la commande sera expédiée, un nouvel e-mail contenant toutes les informations nécessaires au suivi sera déclenché via Tryhard et via notre prestataire de livraison, GLS. Peu de temps avant la livraison, vous recevrez par SMS la date et heure de livraison estimée. Vous pourrez, en utilisant la plateforme mise à sa disposition par notre prestataire, programmer (si vous le souhaitez) une autre date de livraison et/ou demander à vous faire livrer chez un voisin et/ou demander à ce que la commande soit livrée dans un Point Relai de votre choix. Vous pourrez également suivre en temps réel la progression de la livraison. Enfin, dans l’hypothèse où le livreur ne pourrait vous remettre votre commande, elle sera automatiquement déposée dans un Point Relai à proximité de votre domicile."}/>
                    <FaqItem question={"J'ai fait une erreur sur mon adresse de livraison."} answer={"Aucune problème, cela arrive ! Écrivez simplement un email à l'adresse sav@tryhard-gear.com avec vos informations de commande (numéro de commande, nom, prénom, adresse email) ainsi que les corrections à apporter. Nous nous chargerons d'envoyer les modifications à notre transporteur !"}/>
                    <FaqItem question={"Où les claviers Tryhard sont-ils expédiés ?"} answer={"Les claviers Tryhard sont expédiés en France métropolitaine mais aussi en Belgique, Allemagne, au Luxembourg ainsi qu'aux Pays-Bas."}/>
                    <FaqItem question={"Le colis est retourné à l'expéditeur."} answer={"En cas de renvoi à l'expéditeur, notre prestataire GLS ou notre équipe Tryhard essaieront de vous contacter pour vérifier l'adresse postale et comprendre d'où provient l'erreur. Nous procéderons ensuite à un second renvoi. Si nous n'arrivons pas à vous joindre, nous nous réservons le droit d'annuler et rembourser la commande."}/>
                    <FaqItem question={"Que faire si mon colis est perdu ou volé ?"} answer={"Vous disposerez d'un numéro de suivi pour suivre l'évolution de l'expédition de votre commande, depuis l'espace de stockage jusqu'à votre porte. En cas de problème, vous pourrez écrire un e-mail à l'adresse suivante : sav@tryhard-gear.com."}/>
                    <FaqItem question={"J'ai reçu mon clavier griffé ou cassé."} answer={"Nous vous invitons à nous transmettre un email à l'adresse suivante : sav@tryhard-gear.com. Veuillez y joindre une description complète des problèmes rencontrés, des photos et vidéos pour mieux nous aider à analyser la situation, ainsi que votre facture ou une confirmation d'achat."}/>
                </div>
            </div>
            <div>
                <h2>Questions relatives aux commandes et précommandes</h2>
                <div>
                    <FaqItem question={"Quels sont les moyens de paiement ?"} answer={"Le règlement des achats s'effectue par l'intermédiaire du service de paiement sécurisé fourni par carte bancaire du réseau Visa, Eurocard/Mastercard. Le service Paypal sera également proposé très prochainement !"}/>
                    <FaqItem question={"Dans quelle devise sont vos prix ?"} answer={"Les prix affichés sont en euros."}/>
                    <FaqItem question={"Puis-je annuler ma commande ?"} answer={"Il n'est pas possible d'annuler votre commande une fois l'achat effectué. Vous disposez toutefois d'un délai légal de rétraction de 14 jours à compter de la réception de la commande. Si vous souhaitez faire valoir ce droit, contactez-nous sur l'adresse sav@tryhard-gear.com. Notre prestataire vous fera ensuite parvenir un lien de paiement pour les frais de retour. Si l'ensemble du colis - produit et packaging - est bien intact, nous procèderons ensuite au remboursement."}/>
                    <FaqItem question={"Comment fonctionne la précommande ?"} answer={"Seulement 2000 unités ont été produites et livrées chez notre transporteur pour ce premier lancement, mais pas d'inquiétude, nous avons tout prévu ! Si les claviers Tryhard sont en rupture de stock, vous pourrez malgré tout en précommander sur notre site. Une fois le paiement réceptionné, vous recevrez un email de confirmation de précommande et serez d'office inscrit(e) au prochain réassort. Une fois le palier de 2000 claviers précommandés atteint, la production se lancera. Il faudra compter environ 2 à 3 mois pour recevoir votre clavier. Notre conseil : si vous hésitez, ne tardez pas ;) Si le palier n'est pas atteint dans un délai de 3 mois suivant la rupture de stock, nous procéderons au remboursement intégral de votre précommande."}/>
                    <FaqItem question={"Puis-je annuler ma précommande ?"} answer={"Une fois l'achat réalisé, les précommandes ne sont pas annulables et aucun remboursement n'est possible. En revanche, voir question du dessus, si le palier des 2000 précommandes n'est pas atteint dans les 3 mois suivant la rupture, nous procéderons automatiquement au remboursement. Une fois le clavier reçu, vous disposez également d'un délai légal de rétraction de 14 jours."}/>
                    <FaqItem question={"Quand vais-je recevoir ma précommande ?"} answer={"Une fois la précommande passée et le pallier de 2000 unités atteint, nous procéderons à la production puis l'envoi de votre clavier. Il faut compter un délai d'environ 2 à 3 mois. Nous vous tiendrons informé(e) des avancées par e-mail !"}/>
                    <FaqItem question={"Puis-je retourner un clavier si je ne suis pas satisfait ?"} answer={"Vous disposez d'un délai légal de rétraction de 14 jours à compter de la réception de la commande. Si vous souhaitez faire valoir ce droit, contactez-nous sur l'adresse sav@tryhard-gear.com. Notre prestataire vous fera ensuite parvenir un lien de paiement pour les frais de retour, qui sont à votre charge. Si l'ensemble du colis - produit et packaging - est bien intact, nous procèderons ensuite au remboursement."}/>
                    <FaqItem question={"Quelle est votre politique de retour ?"} answer={"Vous disposez d'un délai légal de rétraction de 14 jours à compter de la réception de la commande. Si vous souhaitez faire valoir ce droit, contactez-nous sur l'adresse sav@tryhard-gear.com. Notre prestataire vous fera ensuite parvenir un lien de paiement pour les frais de retour., qui sont à votre charge. Si l'ensemble du colis - produit et packaging - est bien intact, nous procèderons ensuite au remboursement. Passé ce délai, Tryhard n'accepte plus aucun retour. Pour en savoir plus, nous vous incitons à consulter nos Conditions Générales de Vente."}/>
                    <FaqItem question={"Quelle est votre politique d'échange ?"} answer={"Tryhard ne procède à aucun échange, hormis dysfonctionnements majeurs avérés à la réception de la commande. En cas de problème, contactez notre sav à l'adresse sav@tryhard-gear.com, photos et vidéos à l'appui. Si un échange doit effectivement avoir lieu, les stocks étant très limités, Tryhard se réserve le droit de simplement procéder à un remboursement ou de vous proposer de patienter jusqu'au prochain réassort. Pour en savoir plus, n'hésitez pas à consulter nos Conditions Générales de Vente."}/>
                    <FaqItem question={"Comment puis-je obtenir ma facture ?"} answer={"Si vous souhaitez obtenir votre facture, envoyez simplement un e-mail à sav@tryhard-gear.com. Nous vous répondrons dans les plus brefs délais !"}/>
                </div>
            </div>
            <div>
                <h2>Questions relatives aux touches</h2>
                <div>
                    <FaqItem question={"J'aimerais modifier les touches par de nouvelles. Y a-t-il des contraintes spécifiques ?"} answer={"Aucune contrainte. Libre à vous de modifier les touches par de nouvelles, comme bon vous semble ! Notre clavier a spécifiquement été conçu pour permettre à chacun de le personnaliser selon ses besoins et envies."}/>
                    <FaqItem question={"J'aimerais acheter de nouvelles touches. Où puis-je m'en procurer ?"} answer={"Notre site Tryhard ne permet pour le moment pas d'acheter de nouvelles touches. Vous pouvez en revanche vous en procurer vous-même sur Internet. Il n'y a aucune contrainte spécifique."}/>
                    <FaqItem question={"Une ou plusieurs touches de mon clavier sont abîmé(es)."} answer={"Tous nos claviers ont précautionneusement été inspectés avant leur envoi par notre service Contrôle Qualité. Nous vous invitons à nous transmettre un email à l'adresse suivante : sav@tryhard-gear.com. Veuillez y joindre une description complète des problèmes rencontrés, des photos et vidéos pour mieux nous aider à analyser la situation, ainsi que votre facture ou une confirmation d'achat."}/>
                    <FaqItem question={"Certaines touches ne fonctionnent plus."} answer={"Commencez par vérifier si le problème concerne une touche unique, plusieurs touches différentes ou une zone très précise. Une fois les touches identifiées, retirez-les avec l'extracteur et assurez-vous qu'elles ne soient pas sales ou endommâgées. Vérifiez qu'il n'y ait aucun élément bloquant (poussière, miette) puis reclipsez-les manuellement. Vous pouvez également essayer de nettoyer votre clavier. Éteignez et débranchez-le. Utilisez de l'air comprimé ou un aspirateur à faible puissance pour enlever la poussière et les débris entre les touches. Si nécessaire, utilisez un chiffon doux légèrement humidifié avec de l'eau ou une solution de nettoyage douce pour essuyer les touches et le boîtier du clavier. Laissez sécher complètement avant de le rebrancher. Si le problème persiste, il peut être nécessaire de consulter un professionnel ou de contacter notre équipe."}/>
                    <FaqItem question={"Certaines touchent sont difficiles à presser."} answer={"Commencez par vérifier si le problème concerne une touche unique, plusieurs touches différentes ou une zone très précise. Une fois les touches identifiées, retirez-les avec l'extracteur et assurez-vous qu'elles ne soient pas sales ou endommâgées. Vérifiez qu'il n'y ait aucun élément bloquant (poussière, miette) puis reclipsez-les manuellement. Vous pouvez également essayer de nettoyer votre clavier. Éteignez et débranchez-le. Utilisez de l'air comprimé ou un aspirateur à faible puissance pour enlever la poussière et les débris entre les touches. Si nécessaire, utilisez un chiffon doux légèrement humidifié avec de l'eau ou une solution de nettoyage douce pour essuyer les touches et le boîtier du clavier. Laissez sécher complètement avant de le rebrancher."}/>
                    <FaqItem question={"Les touches font un bruit étrange ou ne produisent aucun son."} answer={"Commencez par vérifier si le problème concerne une touche unique, plusieurs touches différentes ou une zone très précise. Une fois les touches identifiées, retirez-les avec l'extracteur et assurez-vous qu'elles ne soient pas sales ou endommâgées. Vérifiez qu'il n'y ait aucun élément bloquant (poussière, miette) puis reclipsez-les manuellement. Vous pouvez également essayer de nettoyer votre clavier. Éteignez et débranchez-le. Utilisez de l'air comprimé ou un aspirateur à faible puissance pour enlever la poussière et les débris entre les touches. Si nécessaire, utilisez un chiffon doux légèrement humidifié avec de l'eau ou une solution de nettoyage douce pour essuyer les touches et le boîtier du clavier. Laissez sécher complètement avant de le rebrancher."}/>
                    <FaqItem question={"Les touches ne sont pas assez éclairées."} answer={"Vous pouvez modifier l'intensité ! Reportez-vous au manuel d'utilisation pour plus d'informations ou utilisez simplement la combinaison suivante afin d'augmenter la luminosité : FN + ↑."}/>
                    <FaqItem question={"Les touches produisent des caractères incorrects."} answer={"Nous vous recommandez de vérifier que la langue du clavier sélectionnée est bien 'Français' (France)."}/>
                    <FaqItem question={"Les touches sont mal alignées ou manquantes."} answer={"Commencez par vérifier si le problème concerne une touche unique, plusieurs touches différentes ou une zone très précise. Une fois les touches identifiées, retirez-les avec l'extracteur et assurez-vous qu'elles ne soient pas sales ou endommâgées. Vérifiez qu'il n'y ait aucun élément bloquant (poussière, miette) puis reclipsez-les manuellement."}/>
                    <FaqItem question={"Il y a des problèmes d'installation ou de configuration des commutateurs."} answer={"Retirez les touches, puis les switches défectueux avec l'extracteur 2-en-1. Vérifiez que les deux switches soient droits. Si l’un d’eux est tordu, redressez-le délicatement. Réinsérez ensuite les switches correctement. Si le problème persiste, il peut être nécessaire de consulter un professionnel ou de joindre notre équipe. En cas de double activation des touches, vérifiez que les pinces à l’intérieur du socket ne soient pas trop décollées. Utilisez une pince fine pour les rapprocher délicatement et assurer une meilleure connexion. Vous pouvez également essayer de nettoyer votre clavier. Éteignez et débranchez-le. Utilisez de l'air comprimé ou un aspirateur à faible puissance pour enlever la poussière et les débris entre les touches. Si nécessaire, utilisez un chiffon doux légèrement humidifié avec de l'eau ou une solution de nettoyage douce pour essuyer les touches et le boîtier du clavier. Laissez sécher complètement avant de le rebrancher. Si le problème persiste, il peut être nécessaire de consulter un professionnel ou de contacter notre équipe."}/>
                    <FaqItem question={"Une de mes touches se détache."} answer={"Commencez par vérifier si le problème concerne une touche unique, plusieurs touches différentes ou une zone très précise. Une fois les touches identifiées, retirez-les avec l'extracteur et assurez-vous qu'elles ne soient pas sales ou endommâgées. Vérifiez qu'il n'y ait aucun élément bloquant (poussière, miette) puis reclipsez-les manuellement."}/>
                </div>
            </div>
            <div>
                <h2>Questions relatives au rétro-éclairage</h2>
                <div>
                    <FaqItem question={"Où puis-je trouver les combinaisons pour modifier le rétro-éclairage ?"} answer={"Nous vous invitons à consulter le manuel d'utilisation qui vous a été transmis avec votre clavier Tryhard. Il contient toutes les indications ! En cas de perte, vous pouvez envoyer un email à l'adresse sav@tryahrd-gear.com."}/>
                    <FaqItem question={"Le setup initial affiche une luminosité blanche. Puis-je mettre une autre couleur ?"} answer={"La luminosité blanche a été installée par défaut. Pour la changer et essayer d'autres coloris, il vous suffit de composer la combinaison suivante : FN + →. N'hésitez pas à consulter notre manuel d'utilisation pour plus d'informations."}/>
                    <FaqItem question={"Je n'arrive pas à configurer le RGB de mon clavier."} answer={"Nous vous invitons à consulter le manuel d'utilisation fourni dans la boite afin d'obtenir plus d'informations."}/>
                    <FaqItem question={"Je souhaite augmenter / diminuer la luminosité de mon clavier."} answer={"Nous vous invitons à consulter le manuel d'utilisation fourni dans la boite afin d'obtenir plus d'informations. Vous pouvez également appliquer directement les combinaisons suivantes pour diminuer la luminosité : FN + ↓ / pour l'augmenter : FN + ↑."}/>
                    <FaqItem question={"Mes LED ne s'allument pas."} answer={"Nous vous invitons à consulter le manuel d'utilisation fourni dans la boite afin d'obtenir plus d'informations. Vous pouvez également appliquer directement les combinaisons suivantes pour allumer le rétro-éclairage : FN + Espace."}/>
                </div>
            </div>
            <div>
                <h2>Questions relatives à la batterie</h2>
                <div>
                    <FaqItem question={"Je viens de recevoir mon clavier. Est-il déjà chargé ?"} answer={"Les claviers Tryhard n'auront pas leur batterie pleinement chargée lors de leur première utilisation. Nous vous recommandons de le brancher en filaire dès que vous ouvrez le colis. La touche FN clignotera alors en rouge, jusqu'à ce que le chargement soit complet (la touche redeviendra blanche)."}/>
                    <FaqItem question={"Quelle est la durée de la batterie ?"} answer={"Tout dépend du mode RGB choisi. En mode 'natif backlight blanche statique', le temps est estimé à 5 heures d'utilisation. En mode RGB, la durée est estimée à environ 10 heures. Sans LEDs allumées enfin, le clavier a une autonomie d'environ 60 heures. Évidemment, seuls les modes Bluetooth et sans fil avec le dongle nécessitent l'utilisation de la batterie."}/>
                    <FaqItem question={"Mon clavier a un problème majeur de batterie."} answer={"Nous vous invitons à nous transmettre un email à l'adresse suivante : sav@tryhard-gear.com. Veuillez y joindre une description complète des problèmes rencontrés, des photos et vidéos pour mieux nous aider à analyser la situation, ainsi que votre facture ou une confirmation d'achat."}/>
                    <FaqItem question={"Mon clavier ne fonctionne pas lorsque je passe sur la batterie. Que puis-je faire ?"} answer={"Repassez sur le mode câblé (filaire) afin que la batterie se recharge. La combinaison FN + B vous donne l'indicateur du niveau de batterie."}/>
                </div>
            </div>
            <div>
                <h2>Questions relatives à la connectivité</h2>
                <div>
                    <FaqItem question={"Mon clavier ne s'allume pas. Que puis-je faire ?"} answer={"Nous vous invitons à repasser sur le mode câblé afin que la batterie se recharge. La combinaison FN + B vous donne l'indicateur du niveau de batterie."}/>
                    <FaqItem question={"Le clavier est-il compatible avec tous les systèmes d'exploitations ?"} answer={"Oui ! Mac OS et Windows, à partir de Windows 7."}/>
                    <FaqItem question={"Je n'arrive pas à connecter mon clavier par Bluetooth."} answer={"Veuillez consulter la section 'Instructions Appairage Bluetooth' dans le manuel d'utilisation qui vous a été envoyé avec votre clavier Tryhard."}/>
                    <FaqItem question={"Je n'arrive pas à connecter mon clavier via le câble."} answer={"Positionnez le sélecteur situé sur la face arrière du clavier sur la position centrale (symbole câble), puis insérez le câble USB-C fourni dans le connecteur central et dans l'ordinateur."}/>
                    <FaqItem question={"Où puis-je trouver le pilote ou logiciel du dongle ?"} answer={"Aucun logiciel n'est nécessaire pour configurer le dongle."}/>
                    <FaqItem question={"Il y a des interférences entre le dongle et le clavier."} answer={"Rapprochez au plus le dongle de votre clavier Tryhard afin d'optimiser ses performances."}/>
                    <FaqItem question={"Mon clavier n'est pas reconnu par mon ordinateur."} answer={"Nos clavier sont reconnus par les systèmes d'exploitation Mac OS et Windows, à partir de Windows 7."}/>
                    <FaqItem question={"J'ai renversé du liquide sur le clavier et il ne fonctionne plus."} answer={"Nous sommes terriblement désolés de cette mauvaise nouvelle ! Vous pouvez déjà commencer par essayer de nettoyer votre clavier. Éteignez et débranchez-le. Utilisez de l'air comprimé ou un aspirateur à faible puissance pour enlever la poussière et les débris entre les touches. Si nécessaire, utilisez un chiffon doux légèrement humidifié avec de l'eau ou une solution de nettoyage douce pour essuyer les touches et le boîtier du clavier. Laissez sécher complètement avant de le rebrancher. Si le clavier n'est plus fonctionnel et que vous souhaitez en recommander un, vous pouvez procéder à un nouvel achat ou vous inscrire sur la liste d'attente si des précommandes sont en cours."}/>
                </div>
            </div>
            <div>
                <h2>Questions relatives au logiciel (software)</h2>
                <div>
                    <FaqItem question={"Y a-t-il des mises à jour du logiciel ?"} answer={"Nous updaterons cette question de la FAQ avec le lien de téléchargement du software (pas encore disponible, nous attendons les premières livraisons du clavier). Si jamais il y a d'éventuelles mises à jour, nous vous tiendrons informés également dans cet espace !"}/>
                    <FaqItem question={"Comment fonctionne la livraison ?"} answer={"Pour le moment, aucune mise à jour n'est prévue, mais si jamais c'est le cas, nous mettrons à jour la réponse à cette question :)"}/>
                    <FaqItem question={"Le clavier prend-il en charge des fonctionnalités avancées telles que les profils d'utilisateur multiples, la programmation de macros, ou la création de raccourcis personnalisés ?"} answer={"Oui ! Difficile de tout expliquer dans ce petit espace mais pour vous donner une première idée, vous pourrez : personnaliser chaque touche et combinaisons FN, créer, exporter et importer des macros ou encore jouer sur le rétro-éclairage par touche, par mode, sur la musique."}/>
                    <FaqItem question={"Comment puis-je sauvegarder et restaurer mes paramètres personnalisés en cas de besoin ?"} answer={"Pensez simplement à sauvegarder vos macros."}/>
                </div>
            </div>
            <div>
                <h2>Contacts</h2>
                <div>
                    <FaqItem question={"J'ai un problème avec mon clavier et je souhaite contacter le service clientèle."} answer={"Nous vous invitons à nous transmettre un email à l'adresse suivante : sav@tryhard-gear.com. Veuillez y joindre une description complète des problèmes rencontrés, des photos et vidéos pour mieux nous aider à analyser la situation, ainsi que votre facture ou une confirmation d'achat."}/>
                    <FaqItem question={"J'aimerais contacter l'équipe presse et partenariats pour une collaboration."} answer={"Vous pouvez écrire un email à l'adresse suivante : contact@tryhard-gear.com. Veuillez noter que cette adresse ne traite en aucun cas des problématiques de SAV."}/>
                    <FaqItem question={"J'ai des questions concernant la politique de confidentialité RGPD de Tryhard."} answer={"Vous pouvez consulter notre politique de confidentialité accessible depuis le footer du site. Si jamais vous souhaitez plus d'informations, vous pouvez également nous contacter à l'adresse rgpd@tryhard-gear.com."}/>
                    <FaqItem question={"J'aimerais contacter CYRILmp4."} answer={"Vous pouvez écrire un email à l'adresse professionnelle de CYRILmp4 : contact@laportecyrilmp4.com"}/>
                    <FaqItem question={"Je souhaite être informé(e) des prochaines nouveautés Tryhard. Comment faire ?"} answer={"Nous vous invitons à vous abonner à notre Newsletter, accessible depuis la page principale, en bas de page. Nos communication seront limitées, pas d'inquiétude et vous pourrez vous désabonner selon vos souhaits. Notre objectif : vous informer des prochains réassorts, des éventuelles offres promotionnelles et surtout de vous alerter des actualités Tryhard (nouveaux produits, nouvelles collections, etc.)."}/>
                </div>
            </div>
        </div>
    </>
}